-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 09:50:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mechanical_workshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mechanical_workshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mechanical_workshop` DEFAULT CHARACTER SET utf8 ;
USE `mechanical_workshop` ;

-- -----------------------------------------------------
-- Table `mechanical_workshop`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`client` (
  `idClient` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cpfcnpj` VARCHAR(14) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`veichle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`veichle` (
  `idVeichle` INT NOT NULL,
  `plate` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVeichle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`veichle_has_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`veichle_has_client` (
  `client_idClient` INT NOT NULL,
  `veichle_idVeichle` INT NOT NULL,
  PRIMARY KEY (`client_idClient`, `veichle_idVeichle`),
  INDEX `fk_Client_has_Veichle_Veichle1_idx` (`veichle_idVeichle` ASC) VISIBLE,
  INDEX `fk_Client_has_Veichle_Client_idx` (`client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Veichle_Client`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `mechanical_workshop`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Veichle_Veichle1`
    FOREIGN KEY (`veichle_idVeichle`)
    REFERENCES `mechanical_workshop`.`veichle` (`idVeichle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`payment_method` (
  `idpayment_method` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpayment_method`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`service_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`service_orders` (
  `idservice_orders` INT NOT NULL,
  `staus` VARCHAR(45) NOT NULL,
  `emission_date` DATE NOT NULL,
  `conclusion_date` DATE NULL,
  `price` DOUBLE NOT NULL,
  `idClient` INT NOT NULL,
  `idPayment_method` INT NOT NULL,
  PRIMARY KEY (`idservice_orders`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  INDEX `idPayment_method_idx` (`idPayment_method` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mechanical_workshop`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPayment_method`
    FOREIGN KEY (`idPayment_method`)
    REFERENCES `mechanical_workshop`.`payment_method` (`idpayment_method`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`services` (
  `idservices` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idservices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`price_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`price_table` (
  `idprice_table` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `idServices` INT NOT NULL,
  PRIMARY KEY (`idprice_table`),
  INDEX `idServices_idx` (`idServices` ASC) VISIBLE,
  CONSTRAINT `idServices`
    FOREIGN KEY (`idServices`)
    REFERENCES `mechanical_workshop`.`services` (`idservices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`mechanical_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`mechanical_parts` (
  `idmechanical_parts` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmechanical_parts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`mechanics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`mechanics` (
  `idmechanics` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `specialty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmechanics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`service_orders_has_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`service_orders_has_services` (
  `service_orders_idservice_orders` INT NOT NULL,
  `services_idservices` INT NOT NULL,
  PRIMARY KEY (`service_orders_idservice_orders`, `services_idservices`),
  INDEX `fk_service_orders_has_services_services1_idx` (`services_idservices` ASC) VISIBLE,
  INDEX `fk_service_orders_has_services_service_orders1_idx` (`service_orders_idservice_orders` ASC) VISIBLE,
  CONSTRAINT `fk_service_orders_has_services_service_orders1`
    FOREIGN KEY (`service_orders_idservice_orders`)
    REFERENCES `mechanical_workshop`.`service_orders` (`idservice_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_orders_has_services_services1`
    FOREIGN KEY (`services_idservices`)
    REFERENCES `mechanical_workshop`.`services` (`idservices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`service_orders_has_mechanics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`service_orders_has_mechanics` (
  `service_orders_idservice_orders` INT NOT NULL,
  `mechanics_idmechanics` INT NOT NULL,
  PRIMARY KEY (`service_orders_idservice_orders`, `mechanics_idmechanics`),
  INDEX `fk_service_orders_has_mechanics_mechanics1_idx` (`mechanics_idmechanics` ASC) VISIBLE,
  INDEX `fk_service_orders_has_mechanics_service_orders1_idx` (`service_orders_idservice_orders` ASC) VISIBLE,
  CONSTRAINT `fk_service_orders_has_mechanics_service_orders1`
    FOREIGN KEY (`service_orders_idservice_orders`)
    REFERENCES `mechanical_workshop`.`service_orders` (`idservice_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_orders_has_mechanics_mechanics1`
    FOREIGN KEY (`mechanics_idmechanics`)
    REFERENCES `mechanical_workshop`.`mechanics` (`idmechanics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mechanical_workshop`.`service_orders_has_mechanical_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanical_workshop`.`service_orders_has_mechanical_parts` (
  `service_orders_idservice_orders` INT NOT NULL,
  `mechanical_parts_idmechanical_parts` INT NOT NULL,
  PRIMARY KEY (`service_orders_idservice_orders`, `mechanical_parts_idmechanical_parts`),
  INDEX `fk_service_orders_has_mechanical_parts_mechanical_parts1_idx` (`mechanical_parts_idmechanical_parts` ASC) VISIBLE,
  INDEX `fk_service_orders_has_mechanical_parts_service_orders1_idx` (`service_orders_idservice_orders` ASC) VISIBLE,
  CONSTRAINT `fk_service_orders_has_mechanical_parts_service_orders1`
    FOREIGN KEY (`service_orders_idservice_orders`)
    REFERENCES `mechanical_workshop`.`service_orders` (`idservice_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_orders_has_mechanical_parts_mechanical_parts1`
    FOREIGN KEY (`mechanical_parts_idmechanical_parts`)
    REFERENCES `mechanical_workshop`.`mechanical_parts` (`idmechanical_parts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from client